export const funnelStages = [
  {
    id: "landing",
    stage: "01",
    name: "Landing",
    description: "Hero page — first impression for all traffic",
    friction: "Split intent creates decision paralysis. Two equal CTAs force a choice before users understand the product, increasing bounce.",
    tests: [
      {
        hypothesis: "Replace dual CTAs with one primary CTA ('Get free legal help') and a secondary text link",
        expectedLift: "+18% first interaction",
        effort: "Low",
      },
      {
        hypothesis: "Embed a 'What's your legal issue?' input directly in the hero — skip the click entirely",
        expectedLift: "+22% engagement rate",
        effort: "Medium",
      },
    ],
    quickWin: "Move the 4.8★ / 35,858 reviews badge directly under the primary CTA — it's buried now.",
    before: {
      label: "Current",
      issue: "Dual CTAs split intent. 'Find a lawyer' implies cost before trust is built.",
      screen: {
        type: "landing-before",
      },
    },
    after: {
      label: "Proposed",
      fix: "Single primary CTA leading with the free AI. Trust signal reinforces zero cost.",
      screen: {
        type: "landing-after",
      },
    },
  },
  {
    id: "engage",
    stage: "02",
    name: "Engage",
    description: "AI chat — user describes their legal issue",
    friction: "Open text input intimidates users who don't know how to phrase a legal problem. Most people don't speak in legal terms.",
    tests: [
      {
        hypothesis: "Show practice area chips first ('Family', 'Employment', 'Property'...) before the open text box",
        expectedLift: "+25% chat completion",
        effort: "Medium",
      },
      {
        hypothesis: "Add contextual example prompts underneath the input: 'e.g. My landlord is keeping my deposit, what are my rights?'",
        expectedLift: "+15% start rate",
        effort: "Low",
      },
    ],
    quickWin: "Add a progress indicator ('~2 min to your report') — uncertainty about time is a top abandonment driver.",
    before: {
      label: "Current",
      issue: "Blank open-text box. No guidance on what to write. Legal phrasing anxiety causes abandonment.",
      screen: { type: "engage-before" },
    },
    after: {
      label: "Proposed",
      fix: "Practice area chips narrow context first. Example prompt removes the blank-page problem.",
      screen: { type: "engage-after" },
    },
  },
  {
    id: "report",
    stage: "03",
    name: "Report",
    description: "AI generates a personalised legal summary",
    friction: "The report feels like the destination, not a step in a journey. Users read it and leave without taking next action.",
    tests: [
      {
        hypothesis: "Pin a 'What should I do next?' CTA to the top of the report before the body content",
        expectedLift: "+30% lawyer connection rate",
        effort: "Low",
      },
      {
        hypothesis: "Embed matched lawyer profiles inline within the report, adjacent to relevant sections",
        expectedLift: "+20% connection rate",
        effort: "High",
      },
    ],
    quickWin: "Add scarcity framing near the lawyer CTA: '4 lawyers in Sydney available for this matter today'.",
    before: {
      label: "Current",
      issue: "Lawyer CTA buried at the bottom after a long report. Most users never scroll that far.",
      screen: { type: "report-before" },
    },
    after: {
      label: "Proposed",
      fix: "Next-step CTA pinned at the top. Lawyer profiles appear inline next to the relevant section.",
      screen: { type: "report-after" },
    },
  },
  {
    id: "convert",
    stage: "04",
    name: "Convert",
    description: "User requests a quote or connects with a lawyer",
    friction: "No expectation setting after submission — users don't know what happens next or when, eroding trust at the last step.",
    tests: [
      {
        hypothesis: "Add 'Expect a response within 2 hours' directly beside the submit button",
        expectedLift: "+20% submit rate",
        effort: "Low",
      },
      {
        hypothesis: "Pre-fill a message template based on the user's report so they don't have to write from scratch",
        expectedLift: "+15% completion rate",
        effort: "Medium",
      },
    ],
    quickWin: "Add 'No obligation — lawyers reach out to you first' below the CTA. Removes the fear of being sold to.",
    before: {
      label: "Current",
      issue: "Generic blank message box. No timeline. No reassurance. High drop-off at the last step.",
      screen: { type: "convert-before" },
    },
    after: {
      label: "Proposed",
      fix: "Pre-filled message from report context. Response time guarantee. No-obligation copy removes fear.",
      screen: { type: "convert-after" },
    },
  },
];

export const seoOpportunities = [
  {
    city: "Sydney",
    area: "Immigration",
    whyValued: "Sydney is Australia's largest immigration hub — it processes more visa applications than any other city. Queries like 'immigration lawyer Sydney' and 'visa help Sydney' attract 8,000–15,000 monthly searches. High-intent, high-fee matters (partner visas avg. $4k+). Zero LawConnect page exists for this combination.",
    topQueries: ["immigration lawyer sydney", "visa lawyer sydney", "partner visa help sydney", "student visa problems sydney"],
    pageStructure: [
      "Hero: 'Find trusted immigration lawyers in Sydney' + star rating",
      "AI hook: 'Not sure where to start? Ask our free AI your immigration question'",
      "Practice areas: partner visas, student visas, work visas, citizenship, appeals",
      "Featured lawyers: top-rated Sydney immigration specialists",
      "FAQ: 'How much does an immigration lawyer cost in Sydney?', visa processing times, etc.",
      "Suburb links: CBD, Parramatta, Chatswood, Hurstville (high migrant populations)",
    ],
  },
  {
    city: "Melbourne",
    area: "Immigration",
    whyValued: "Melbourne has Australia's second-largest immigrant population and a major international student cohort. 'Immigration lawyer Melbourne' drives 6,000–10,000 monthly searches. The combination of student visa issues, employer-sponsored visas, and permanent residency applications makes this a high-volume, high-value market.",
    topQueries: ["immigration lawyer melbourne", "work visa lawyer melbourne", "permanent residency lawyer melbourne", "student visa issues melbourne"],
    pageStructure: [
      "Hero with Melbourne-specific trust signals (no. of immigration lawyers on platform)",
      "AI hook: 'Unsure about your visa options? Get a free answer in 2 minutes'",
      "Visa type navigator: skilled, family, student, business, humanitarian",
      "Lawyer grid filtered to immigration specialists",
      "FAQ targeting common Melbourne queries (employer sponsorship, 482 visa, etc.)",
      "Suburb links: CBD, Footscray, Box Hill, Springvale",
    ],
  },
  {
    city: "Brisbane",
    area: "Personal Injury",
    whyValued: "Queensland runs a no-fault injury scheme (WorkCover + CTP) but personal injury claims outside that scheme are still actively litigated. 'Personal injury lawyer Brisbane' gets 4,000–7,000 monthly searches. Claim values are high (avg. $80k+) and most claimants start by researching online — perfect for the AI hook.",
    topQueries: ["personal injury lawyer brisbane", "compensation lawyer brisbane", "work injury claim brisbane", "car accident lawyer brisbane"],
    pageStructure: [
      "Hero: 'Find Personal Injury Lawyers in Brisbane — Free Initial Guidance'",
      "AI hook: 'Were you injured? Find out if you have a claim — free, in 2 minutes'",
      "Claim types: WorkCover, CTP, public liability, medical negligence, slip and fall",
      "No-win no-fee explanation (critical trust signal for this practice area)",
      "Lawyer directory filtered to personal injury specialists",
      "FAQ: 'How long do I have to make a claim in Queensland?', 'What's my case worth?'",
    ],
  },
  {
    city: "Perth",
    area: "Personal Injury",
    whyValued: "WA's mining and resources sector generates a disproportionately high volume of workplace injury claims. 'Personal injury lawyer Perth' gets 3,000–5,000 monthly searches with unusually high claim values (mining injuries avg. $120k+). Claimants are specifically looking for WA-jurisdiction specialists — a page LawConnect doesn't have.",
    topQueries: ["personal injury lawyer perth", "workers compensation perth", "mining injury lawyer perth", "workplace accident perth"],
    pageStructure: [
      "Hero: 'Personal Injury Lawyers in Perth — Specialising in WA Claims'",
      "AI hook: 'Injured at work? Know your WA rights for free before you call anyone'",
      "Sector callouts: mining/resources, construction, public sector",
      "WorkCover WA process explainer (builds trust + SEO)",
      "Lawyer directory: WA-admitted personal injury specialists",
      "FAQ: WA limitation periods, WorkCover vs. common law, 'do I need a lawyer?'",
    ],
  },
  {
    city: "Canberra",
    area: "Employment Law",
    whyValued: "Canberra has Australia's highest concentration of public servants — a workforce with specific employment law needs (public sector dismissal, APS conduct, enterprise bargaining disputes). 'Employment lawyer Canberra' gets 1,500–3,000 monthly searches but has almost zero specialist content. Low competition + captive high-intent audience.",
    topQueries: ["employment lawyer canberra", "unfair dismissal canberra", "public service lawyer canberra", "workplace discrimination canberra"],
    pageStructure: [
      "Hero: 'Employment Lawyers in Canberra — APS & Private Sector'",
      "AI hook: 'Not sure if you were treated fairly at work? Ask the free AI first'",
      "Audience callouts: APS employees, defence contractors, private sector",
      "Matter types: unfair dismissal, general protections, enterprise agreements, discrimination",
      "Lawyer directory: ACT-admitted employment specialists",
      "FAQ: APS Code of Conduct, Fair Work vs. public sector jurisdiction, time limits",
    ],
  },
];

export const cities = ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Hobart", "Darwin"];

export const practiceAreas = [
  "Family Law",
  "Property Law",
  "Employment Law",
  "Criminal Law",
  "Commercial Law",
  "Estate Planning",
  "Personal Injury",
  "Immigration",
  "IP",
  "Litigation",
];

// "exists" = LawConnect page confirmed, "gap" = missing, "opportunity" = missing + high search volume
export const seoGrid: Record<string, Record<string, "exists" | "gap" | "opportunity">> = {
  Sydney: {
    "Family Law": "exists",
    "Property Law": "exists",
    "Employment Law": "exists",
    "Criminal Law": "exists",
    "Commercial Law": "exists",
    "Estate Planning": "gap",
    "Personal Injury": "exists",
    "Immigration": "opportunity",
    "IP": "gap",
    "Litigation": "gap",
  },
  Melbourne: {
    "Family Law": "exists",
    "Property Law": "exists",
    "Employment Law": "exists",
    "Criminal Law": "exists",
    "Commercial Law": "gap",
    "Estate Planning": "gap",
    "Personal Injury": "exists",
    "Immigration": "opportunity",
    "IP": "gap",
    "Litigation": "gap",
  },
  Brisbane: {
    "Family Law": "exists",
    "Property Law": "exists",
    "Employment Law": "gap",
    "Criminal Law": "exists",
    "Commercial Law": "gap",
    "Estate Planning": "gap",
    "Personal Injury": "opportunity",
    "Immigration": "gap",
    "IP": "gap",
    "Litigation": "gap",
  },
  Perth: {
    "Family Law": "exists",
    "Property Law": "gap",
    "Employment Law": "gap",
    "Criminal Law": "exists",
    "Commercial Law": "gap",
    "Estate Planning": "gap",
    "Personal Injury": "opportunity",
    "Immigration": "gap",
    "IP": "gap",
    "Litigation": "gap",
  },
  Adelaide: {
    "Family Law": "exists",
    "Property Law": "gap",
    "Employment Law": "gap",
    "Criminal Law": "gap",
    "Commercial Law": "gap",
    "Estate Planning": "gap",
    "Personal Injury": "gap",
    "Immigration": "gap",
    "IP": "gap",
    "Litigation": "gap",
  },
  Canberra: {
    "Family Law": "gap",
    "Property Law": "gap",
    "Employment Law": "opportunity",
    "Criminal Law": "gap",
    "Commercial Law": "gap",
    "Estate Planning": "gap",
    "Personal Injury": "gap",
    "Immigration": "gap",
    "IP": "gap",
    "Litigation": "gap",
  },
  Hobart: {
    "Family Law": "gap",
    "Property Law": "gap",
    "Employment Law": "gap",
    "Criminal Law": "gap",
    "Commercial Law": "gap",
    "Estate Planning": "gap",
    "Personal Injury": "gap",
    "Immigration": "gap",
    "IP": "gap",
    "Litigation": "gap",
  },
  Darwin: {
    "Family Law": "gap",
    "Property Law": "gap",
    "Employment Law": "gap",
    "Criminal Law": "gap",
    "Commercial Law": "gap",
    "Estate Planning": "gap",
    "Personal Injury": "gap",
    "Immigration": "gap",
    "IP": "gap",
    "Litigation": "gap",
  },
};

export const currentCommsAudit = {
  received: [
    {
      type: "email",
      label: "Welcome email",
      timing: "Immediately on signup",
      status: "firing",
      subject: "Welcome to LawConnect!",
      preview: "Thank you for creating an account — and welcome to LawConnect!",
      issues: [
        "Generic copy — no mention of the user's specific legal matter",
        "CTA is 'View my account →' — doesn't resume the legal journey",
        "No urgency, no next step, no value delivered",
        "Opportunity to personalise by practice area completely missed",
      ],
    },
    {
      type: "sms",
      label: "Abandonment SMS",
      timing: "~30 min after incomplete enquiry",
      status: "broken",
      subject: "Hi italo, you started a legal enquiry with us but didn't finish.",
      preview: "If you'd still like help matching with a lawyer, tap to confirm: [link]",
      issues: [
        "Sent twice — duplicate SMS within 5 minutes (trust-eroding)",
        "Confirmation link resolves to admin.finchly.com.au — looks like spam",
        "Clicking the confirmation link returns 'Invalid link' — conversion lost",
        "Opt-out link leads to a dead-end page with no re-engagement offer",
        "No SMS sent after that — conversation fully abandoned",
      ],
    },
  ],
  missing: [
    { trigger: "AI chat completed", expected: "Report delivery email with summary + lawyer CTA", impact: "High" },
    { trigger: "Report viewed, no lawyer contact within 1h", expected: "Matched lawyers follow-up email", impact: "High" },
    { trigger: "Report viewed, no lawyer contact within 24h", expected: "Social proof + re-engagement email", impact: "High" },
    { trigger: "Lawyer matched / enquiry sent", expected: "What to expect next email", impact: "Medium" },
    { trigger: "7 days post-connection", expected: "How did it go? + review request", impact: "Medium" },
    { trigger: "30 days inactive", expected: "Re-engagement with new matter or referral ask", impact: "Low" },
  ],
};

export const proposedSequences = [
  {
    id: "onboarding",
    name: "Welcome & Activation",
    trigger: "Account created",
    goal: "Get user to complete AI chat or submit legal enquiry",
    color: "blue",
    emails: [
      {
        num: 1,
        channel: "Email",
        timing: "Immediately",
        subject: "Your LawConnect account is ready — here's where to start",
        preview: "You created an account but haven't asked your question yet. It takes 2 minutes.",
        body: "Hi [First name], you're set up — but the most useful thing you can do right now is ask your legal question. Our AI gives you a plain-English answer in about 2 minutes, free. No lawyers involved yet, no cost. Just clarity on where you stand.\n\nWhat's on your mind?",
        cta: "Ask my legal question →",
        fix: "Replace generic 'View my account' with a direct path to the product's core value",
      },
      {
        num: 2,
        channel: "Email",
        timing: "Day 2 (if no chat started)",
        subject: "Not sure how to start? Try one of these",
        preview: "The most common legal questions people ask us — maybe one sounds familiar.",
        body: "Hi [First name], if you're not sure how to phrase your legal question, here are some of the most common things people ask LawConnect:\n\n• 'My landlord is withholding my bond — what are my options?'\n• 'I think I was unfairly dismissed — do I have a case?'\n• 'My spouse and I are separating — what happens to the house?'\n\nYou don't need legal language. Just describe your situation in plain English.",
        cta: "Start with a question →",
        fix: "Remove blank-page anxiety with worked examples. Drives chat starts from cold users.",
      },
    ],
  },
  {
    id: "report",
    name: "Report → Lawyer Connection",
    trigger: "AI report generated",
    goal: "Convert report viewer to lawyer enquiry",
    color: "violet",
    emails: [
      {
        num: 1,
        channel: "Email",
        timing: "Immediately after report",
        subject: "Your legal report is ready",
        preview: "Here's what the AI found about your [family law / property / employment] matter.",
        body: "Hi [First name], your LawConnect report is ready. Based on what you shared:\n\n[AI-generated 2-sentence summary of their matter]\n\nBased on your situation, here are 3 lawyers in [their city] who specialise in [their practice area]:\n\n[Lawyer 1 — name, rating, reviews]\n[Lawyer 2 — name, rating, reviews]\n[Lawyer 3 — name, rating, reviews]\n\nYou can connect with any of them at no obligation — they'll reach out to you first.",
        cta: "View my matched lawyers →",
        fix: "This email doesn't exist today. It's the highest-leverage missing touchpoint — user is at peak intent the moment after the report.",
      },
      {
        num: 2,
        channel: "Email",
        timing: "24h later (if no lawyer contact)",
        subject: "[First name], your matter is still open",
        preview: "4 lawyers in Sydney have been shown your enquiry. Here's how to move forward.",
        body: "Hi [First name], your legal report is still sitting in your account. A few things worth knowing:\n\n• Connecting with a lawyer doesn't mean you're hiring one\n• The initial response is free\n• Most people who connect with a lawyer feel significantly less stressed afterwards\n\nYour matched lawyers are still available.",
        cta: "Review my matched lawyers →",
        fix: "Objection handling email — removes the fear of commitment that stops report viewers from converting.",
      },
      {
        num: 3,
        channel: "SMS",
        timing: "48h later (if no lawyer contact)",
        subject: "LawConnect: Your report is ready and 3 lawyers match your matter. Reply STOP to opt out.",
        preview: "",
        body: "Hi [First name], 3 lawyers match your [practice area] matter on LawConnect. Connecting is free and there's no obligation. View them here: [link]",
        cta: "[Short link to matched lawyers]",
        fix: "Single SMS (not duplicate). Links to lawconnect.com not admin.finchly.com.au. Sent only if email hasn't converted.",
      },
    ],
  },
  {
    id: "abandonment",
    name: "Enquiry Abandonment Recovery",
    trigger: "Chat started but report not completed",
    goal: "Bring user back to finish their enquiry",
    color: "amber",
    emails: [
      {
        num: 1,
        channel: "Email",
        timing: "1h after abandonment",
        subject: "You were close — your legal question isn't finished",
        preview: "It only takes another minute to get your answer.",
        body: "Hi [First name], you started a legal question with us but didn't quite finish. That's okay — it happens.\n\nYour question is saved. Click below to pick up where you left off and get your free legal summary.",
        cta: "Finish my question →",
        fix: "Replace the current SMS (which has a broken link) with a reliable email first. Easier to track, easier to fix.",
      },
      {
        num: 2,
        channel: "SMS",
        timing: "3h after abandonment (if email not opened)",
        subject: "LawConnect: You started a legal question but didn't finish. Tap to continue: [link]",
        preview: "",
        body: "Hi [First name], your legal question is saved on LawConnect. Tap to finish and get your free answer: [lawconnect.com/continue/[id]]",
        cta: "[lawconnect.com link — not admin.finchly.com.au]",
        fix: "Single SMS only. Use lawconnect.com domain. Fix the broken magic link before sending. No duplicate sends.",
      },
    ],
  },
  {
    id: "post-connect",
    name: "Post-Connection Nurture",
    trigger: "User connects with a lawyer",
    goal: "Reduce anxiety, drive review, generate referrals",
    color: "emerald",
    emails: [
      {
        num: 1,
        channel: "Email",
        timing: "Immediately after connection",
        subject: "You've connected with [Lawyer name] — here's what to expect",
        preview: "They'll reach out within 2 hours. Here's how to prepare.",
        body: "Hi [First name], you've connected with [Lawyer name]. Here's what happens next:\n\n• They'll review your matter and respond within 2 hours\n• Their first response is free — no obligation to engage\n• You can message them directly through your LawConnect account\n\nWhile you wait, it might help to gather any relevant documents (contracts, messages, correspondence).",
        cta: "View my enquiry →",
        fix: "Removes the anxiety vacuum after submitting. Sets expectations. Currently nothing is sent after connection.",
      },
      {
        num: 2,
        channel: "Email",
        timing: "7 days after connection",
        subject: "How did it go with [Lawyer name]?",
        preview: "A quick note — and a small ask if things went well.",
        body: "Hi [First name], it's been a week since you connected with [Lawyer name] through LawConnect. We hope your matter is moving in the right direction.\n\nIf the experience was good, leaving a review makes a real difference — it helps others facing the same situation find the right lawyer faster.",
        cta: "Leave a review →",
        fix: "Review collection is the engine behind LawConnect's 4.8★ rating. This email should be automated for every completed connection.",
      },
    ],
  },
];

export const ninetyDayPlan = {
  phases: [
    {
      id: "diagnose",
      phase: "Phase 1",
      label: "Diagnose & Listen",
      days: "Days 1–30",
      theme: "Don't touch the dials yet. Understand the machine.",
      color: "blue",
      goal: "Build a complete picture of what's working, what's broken, and where the biggest leverage is — before making any changes.",
      weeks: [
        {
          week: "Week 1",
          focus: "Stakeholder immersion",
          tasks: [
            "Meet co-founders: understand the 12-month vision and what's already been tried",
            "Meet product, engineering, and data teams — map what's measurable and what isn't",
            "Sit in on 3 real user sessions or watch session recordings",
            "Review all current campaign performance (SEM, SEO, email, paid social)",
          ],
        },
        {
          week: "Week 2",
          focus: "Full funnel audit",
          tasks: [
            "Pull conversion rates at every funnel stage with real data (not estimates)",
            "Identify the single biggest drop-off point",
            "Audit the email/SMS flows end-to-end — fix the broken abandonment SMS immediately",
            "Map all current SEO pages and their traffic performance",
          ],
        },
        {
          week: "Week 3",
          focus: "Competitive & channel landscape",
          tasks: [
            "Analyse top 5 SEM competitors — what keywords they own, what we're losing",
            "Audit the programmatic SEO gap (city × practice area coverage)",
            "Review CAC by channel — identify which channels are most efficient",
            "Benchmark LTV:CAC across lawyer acquisition and consumer acquisition",
          ],
        },
        {
          week: "Week 4",
          focus: "Prioritisation & planning",
          tasks: [
            "Present findings to co-founders: top 5 highest-leverage opportunities ranked by impact/effort",
            "Agree on Q2 growth targets: report completions, lawyer connections, CAC targets",
            "Draft 60-day execution plan with owners and timelines",
            "Begin hiring brief for first growth hire (performance marketer or data analyst)",
          ],
        },
      ],
      keyMetric: "Baseline established for all funnel KPIs",
      deliverable: "Growth audit presentation to co-founders with prioritised opportunity stack",
    },
    {
      id: "fix",
      phase: "Phase 2",
      label: "Fix & Launch",
      days: "Days 31–60",
      theme: "Fix the broken. Launch the quick wins. Prove the model.",
      color: "violet",
      goal: "Ship the highest-impact, lowest-effort changes. Get the first data from A/B tests. Establish the growth team's operating rhythm.",
      weeks: [
        {
          week: "Week 5",
          focus: "Fix the broken flows",
          tasks: [
            "Fix the abandonment SMS: single send, lawconnect.com domain, working magic link",
            "Launch the post-report email (highest missing touchpoint — fires immediately after AI report)",
            "Fix the 'Not interested' dead-end opt-out page with a soft re-engagement offer",
            "Set up proper UTM tracking across all channels",
          ],
        },
        {
          week: "Week 6",
          focus: "First A/B tests live",
          tasks: [
            "Launch hero CTA test: 'Find a lawyer' vs 'Ask the AI — it's free'",
            "Launch retargeting campaign for report viewers who didn't connect with a lawyer",
            "Deploy FAQ and LocalBusiness schema markup on all city/practice area pages",
            "Publish first 5 high-priority SEO gap pages (Sydney Immigration, Melbourne Immigration, Brisbane Personal Injury)",
          ],
        },
        {
          week: "Week 7",
          focus: "Paid acquisition test",
          tasks: [
            "Launch first social campaign with AI-as-hook creative (3 ad variants, pain-point led)",
            "Test intent-matched SEM copy: route informational queries to AI chat, not lawyer directory",
            "Set up email sequences: welcome activation, report-to-lawyer, post-connection nurture",
            "Brief and onboard first growth hire",
          ],
        },
        {
          week: "Week 8",
          focus: "Read the data",
          tasks: [
            "Review A/B test results from hero CTA — ship the winner",
            "Assess CAC from first social campaign — optimise or cut underperforming ad sets",
            "Review SEO performance of new pages — adjust structure based on early signals",
            "Weekly growth metrics review established as a standing team ritual",
          ],
        },
      ],
      keyMetric: "Report-to-lawyer connection rate +20%",
      deliverable: "Live A/B tests, fixed comms flows, first 5 SEO gap pages, retargeting live",
    },
    {
      id: "scale",
      phase: "Phase 3",
      label: "Scale & Build",
      days: "Days 61–90",
      theme: "Double down on what's working. Build for scale.",
      color: "emerald",
      goal: "Take validated wins and scale them. Lay the foundation for programmatic SEO at full scale, international research, and a high-performing growth team.",
      weeks: [
        {
          week: "Week 9",
          focus: "Scale what's working",
          tasks: [
            "Scale the winning paid social creative — increase budget on top-performing ad sets",
            "Expand programmatic SEO to remaining 30+ gap pages using Claude-assisted generation",
            "Launch practice-area specific landing pages matched to top SEM intent queries",
            "A/B test the AI chat engage screen: open text vs. practice area chips",
          ],
        },
        {
          week: "Week 10",
          focus: "International groundwork",
          tasks: [
            "Research brief: UK and NZ as first international markets (common law, English-speaking)",
            "Assess technical lift for /en-gb and /en-nz URL structures",
            "Identify top 10 SEO opportunities in UK market using existing content as base",
            "Review lawyer supply-side readiness for international expansion",
          ],
        },
        {
          week: "Week 11",
          focus: "Team & process",
          tasks: [
            "First growth hire onboarded and owning a channel independently",
            "Growth team weekly cadence established: experiment backlog, results review, next sprint",
            "Attribution model reviewed and agreed with data team",
            "Referral program brief drafted — how to activate lawyers as a consumer acquisition channel",
          ],
        },
        {
          week: "Week 12",
          focus: "90-day review & Q2 plan",
          tasks: [
            "Present 90-day results to co-founders: wins, learnings, and what's next",
            "Propose Q2 growth budget with channel allocation and CPA targets",
            "Set 6-month OKRs with the team",
            "Publish first 'state of growth' internal doc — establishes the team's operating standard",
          ],
        },
      ],
      keyMetric: "CAC down 15%, lawyer connection rate up 30% vs Day 1 baseline",
      deliverable: "90-day results deck, Q2 budget proposal, full SEO gap coverage, international brief",
    },
  ],
  metrics: [
    { name: "Report completion rate", baseline: "~45%", target: "65%+", timeframe: "Day 60" },
    { name: "Report → lawyer connection", baseline: "~12%", target: "20%+", timeframe: "Day 60" },
    { name: "Abandonment recovery rate", baseline: "Broken", target: "8%+", timeframe: "Day 45" },
    { name: "SEO gap pages live", baseline: "0 of 43", target: "43 of 43", timeframe: "Day 75" },
    { name: "Email sequence coverage", baseline: "1 email only", target: "4 sequences live", timeframe: "Day 45" },
    { name: "Blended CAC", baseline: "Establish baseline", target: "−15%", timeframe: "Day 90" },
  ],
};

export const socialAds = [
  {
    platform: "Instagram / Facebook",
    intent: "Awareness — pain point hook",
    format: "Static image + caption",
    hook: "Landlord keeping your bond?",
    body: "Most renters don't know their rights — and landlords count on that. Ask LawConnect's free AI and find out exactly where you stand in 2 minutes.",
    cta: "Ask for free →",
    targetAudience: "25–45, renters, metro AU",
    estimatedCPL: "$8–14",
    color: "violet",
  },
  {
    platform: "Instagram / TikTok",
    intent: "Awareness — emotional hook",
    format: "Short video (15s) or Reel",
    hook: "Before you hire a lawyer, do this.",
    body: "Ask LawConnect's free AI your legal question. Get a plain-English answer in minutes. Then decide if you need a lawyer — with confidence.",
    cta: "Try it free",
    targetAudience: "28–50, life-event triggers",
    estimatedCPL: "$6–12",
    color: "pink",
  },
  {
    platform: "Google Display / YouTube",
    intent: "Retargeting — report viewers",
    format: "Display banner / pre-roll",
    hook: "Still thinking about your legal matter?",
    body: "You've already got your free report. A matched lawyer is one step away — no obligation to engage.",
    cta: "Connect with a lawyer",
    targetAudience: "Report viewers, 7-day window",
    estimatedCPL: "$18–30",
    color: "blue",
  },
];

export const semAds = [
  {
    query: '"family lawyer sydney cost"',
    intent: "High — price anxiety, early stage",
    headline1: "Family Law Questions? Ask Free",
    headline2: "Get Plain-English Answers First",
    headline3: "No Obligation · Trusted by 35,000+",
    description: "Understand your situation before you engage a lawyer. LawConnect's free AI answers your family law questions instantly — then matches you with top Sydney lawyers.",
    landingPage: "/en-au/find/family-law/nsw/sydney",
    insight: "Current page leads with lawyer directory. Opportunity: route this traffic to the AI chat first — converts warmer because user gets value before being asked to engage.",
  },
  {
    query: '"unfair dismissal rights australia"',
    intent: "High — urgency, information-seeking",
    headline1: "Were You Unfairly Dismissed?",
    headline2: "Free AI Explains Your Rights",
    headline3: "Answer in 2 Min · Talk to a Lawyer",
    description: "Find out if you have a case — instantly and for free. Our AI breaks down unfair dismissal law in plain English, then connects you with employment lawyers who can help.",
    landingPage: "/en-au/find/employment-law/nsw/sydney",
    insight: "Query shows research intent, not hire intent. The AI tool is the perfect offer here — give them the answer, earn their trust, then introduce lawyers.",
  },
  {
    query: '"can my landlord keep my bond"',
    intent: "Medium — informational, high volume",
    headline1: "Can Your Landlord Keep Your Bond?",
    headline2: "Free Legal Answer in 2 Minutes",
    headline3: "LawConnect AI · No Sign-Up Needed",
    description: "Ask our free AI the exact question on your mind. Get a clear, jargon-free answer — and know your options before you act.",
    landingPage: "/en-au/chat?q=bond+dispute",
    insight: "This query is pure information intent. Route directly to pre-filled AI chat — skip the lawyer directory entirely. Conversion will be significantly higher.",
  },
];

export const pageComparison = {
  current: {
    label: "Current",
    headline: "Find trusted lawyers across Australia",
    subheadline: "Tell us about your situation, and we'll match you with a lawyer suited to your needs, giving you a clear and confident starting point.",
    ctas: ["Find a lawyer", "Ask a question"],
    trustSignal: "4.8★ · 35,858 verified client reviews",
    issue: "Leads with the lawyer directory. Implies cost and commitment before the user is ready. 'Find a lawyer' CTA requires trust the visitor hasn't built yet.",
    color: "zinc",
  },
  proposed: {
    label: "Proposed",
    headline: "Understand your rights before you call a lawyer.",
    subheadline: "Ask LawConnect's free AI any legal question. Get a plain-English answer in minutes — then decide if you need legal help.",
    ctas: ["Ask the AI — it's free", "Browse lawyers"],
    trustSignal: "4.8★ · 35,858 people helped · No sign-up needed",
    rationale: "Leads with the zero-friction offer (free AI). Repositions the product as an answer machine first, lawyer marketplace second. Removes the commitment signal entirely from the primary CTA.",
    color: "violet",
  },
};

export const aiFlowSteps = [
  {
    step: "01",
    channel: "Social / SEM",
    label: "The hook",
    description: "Ad targets a specific pain point — not a generic 'need a lawyer?' message. User clicks because the hook matches their exact situation.",
    example: '"Landlord keeping your bond? Find out your rights free."',
    type: "ad",
  },
  {
    step: "02",
    channel: "Landing Page",
    label: "Low-friction entry",
    description: "Landing page matches the ad copy exactly. Primary CTA is the free AI tool — no commitment, no sign-up. Trust signals visible but secondary.",
    example: '"Can my landlord keep my bond?" → Ask the AI',
    type: "landing",
  },
  {
    step: "03",
    channel: "AI Chat",
    label: "Value delivered",
    description: "User gets a real answer to their real question in under 2 minutes. No jargon. No sales pitch. This is the moment trust is built.",
    example: "AI explains bond dispute rules, tenant rights, and what documentation is needed.",
    type: "ai",
  },
  {
    step: "04",
    channel: "Report",
    label: "The warm handoff",
    description: "Report summarises the conversation and, crucially, frames next steps. Lawyer CTAs appear inline, contextualised to the specific matter — not as a generic upsell.",
    example: '"Based on your situation, here are 3 property lawyers in Sydney who can help."',
    type: "report",
  },
  {
    step: "05",
    channel: "Lawyer Connection",
    label: "Conversion",
    description: "User connects with a matched lawyer from a position of confidence — they understand their situation. Conversion quality is higher; lawyers report better-prepared clients.",
    example: "User submits job. Lawyer responds within 2 hours.",
    type: "convert",
  },
];

export const growthInitiatives = [
  // High Impact, Low Effort
  { id: 1, name: "Optimise hero CTA copy + placement", impact: 85, effort: 20, category: "CRO", description: "Single primary CTA, social proof directly below." },
  { id: 2, name: "Schema markup on all city/practice pages", impact: 75, effort: 25, category: "SEO", description: "FAQ and LocalBusiness schema — quick organic lift." },
  { id: 3, name: "Retargeting for report viewers", impact: 80, effort: 30, category: "Paid", description: "People who got a report but didn't connect with a lawyer are warm leads." },
  { id: 4, name: "Email sequence post-report", impact: 70, effort: 25, category: "Email", description: "3-email drip to non-converters: remind, reframe, urgency." },
  // High Impact, High Effort
  { id: 5, name: "Fill all SEO city × practice area gaps", impact: 90, effort: 75, category: "SEO", description: "38+ missing pages. Programmatic generation with Claude — weeks of organic traffic unlocked." },
  { id: 6, name: "AI personalisation by traffic source", impact: 85, effort: 80, category: "CRO", description: "Show different hero copy for 'divorce lawyer' vs 'business contract' SEM traffic." },
  { id: 7, name: "Lawyer referral / incentive program", impact: 80, effort: 70, category: "Growth", description: "Lawyers refer consumers. Closes the network loop." },
  { id: 8, name: "International expansion — UK/NZ", impact: 88, effort: 85, category: "Expansion", description: "Same common law system. URL structure and content are mostly reusable." },
  // Low Impact, Low Effort
  { id: 9, name: "Social proof widget on all pages", impact: 35, effort: 15, category: "CRO", description: "Surface the 4.8★ / 35k reviews everywhere, not just the homepage." },
  { id: 10, name: "FAQ schema on existing pages", impact: 40, effort: 20, category: "SEO", description: "Rich results for common legal questions — free impressions." },
  { id: 11, name: "Exit-intent popup on report page", impact: 30, effort: 20, category: "CRO", description: "Capture email before they leave without connecting to a lawyer." },
  // Low Impact, High Effort
  { id: 12, name: "Brand awareness OOH / TV campaign", impact: 30, effort: 90, category: "Brand", description: "Too early — performance channels should be saturated first." },
  { id: 13, name: "Mobile app development", impact: 35, effort: 95, category: "Product", description: "Low marginal benefit over a well-optimised mobile web experience right now." },
];
